force-app/main/default/objects/Equipamento__c/Equipamento__c.object-meta.xml
<CustomObject>
    <label>Equipamento</label>
    <nameField>
        <displayFormat>EQ-{0000}</displayFormat>
        <label>Nome de Equipamento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Equipamentos</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Equipamento__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Operacional</fullName>
            </value>
            <value>
                <fullName>Em manutenção</fullName>
            </value>
            <value>
                <fullName>Com defeito</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/EquipamentoTriggerHandler.cls
public class EquipamentoTriggerHandler {
    
    public static void verificarEquipamentoComDefeito(List<Equipamento__c> equipamentosNovos, Map<Id, Equipamento__c> equipamentosAntigos) {
        
        List<Case> chamadosParaCriar = new List<Case>();
        
        for (Equipamento__c equip : equipamentosNovos) {
            
            Equipamento__c equipAntigo = equipamentosAntigos.get(equip.Id);
            
            if (equip.Status__c == 'Com Defeito' && equipAntigo.Status__c != 'Com Defeito') {
                Case novoChamado = new Case(); 
                
                novoChamado.Subject = 'Manutenção Urgente: ' + equip.Name;
                novoChamado.Status = 'New';
                novoChamado.Priority = 'High';
                novoChamado.Description = 'Sistema detectou falha no equipamento. Iniciar diagnóstico.';
                novoChamado.Equipamento__c = equip.Id;
                
                chamadosParaCriar.add(novoChamado);
            }
        }
        
        // Linha 29 agora vai rodar lisa!
        if (!chamadosParaCriar.isEmpty()) {
            insert chamadosParaCriar;
        }
    }
}